photo_renovation_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_core/', include('site_core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('site_core.urls'))
]

handler404 = 'site_core.views.view_404'

site_core/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from site_core import views
from site_core.views import HomeView, PhotoCreateView, PhotoListView, \
    SignUpView, ContactView, PhotoDeleteView

app_name = 'site_core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create_photo/', PhotoCreateView.as_view(), name = 'create_photo'),
    path('list_photo/', PhotoListView.as_view(), name = 'list_photo'),
    path('signup/', SignUpView.as_view(), name = 'signup'),
    path('contact_form/', ContactView.as_view(), name = 'contact_form'),
    path('gallery/', views.gallery, name='gallery'),
    path('email_success/', views.email_success, name = 'email_success'),
    path('photo_delete/<int:pk>', PhotoDeleteView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'site_core.views.view_404'

site_core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Photo(models.Model):
    '''Use the 'Photo reconstruction' tab to create an instance of this class.
    These instances are displayed in the "my photos" tab.
    This class is used by PhotoCreateView, PhotoDeleteView and PhotoListView in the vievs.py file'''

    description = models.CharField(max_length=150, default=None)
    photo = models.ImageField(upload_to='media/photos')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.description}"

class Contact(models.Model):

    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

site_core/forms.py
from datetime import datetime
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from .models import Contact


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "email")

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

    def send_email(self):
        '''This method allows you to send an e-mail to the user with the information contained in the contact form.'''

        now = datetime.now()
        date_and_time_string = now.strftime("%d/%m/%Y %H:%M:%S")
        auto_message = 'On {} at {} we received your message with the following content: \n\n{}\n{} \n\n We will try to answer it  soon. Please do not reply to this message. \n\n The photo renovation website team.'.format(date_and_time_string.split()[0], date_and_time_string.split()[1], self.cleaned_data['subject'], self.cleaned_data['message'])

        send_mail('Photo renovation website - contact', message = auto_message, from_email = 'test.photo.renovation.website@gmail.com', recipient_list = [self.cleaned_data['email'], ], fail_silently=False)

site_core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from site_core.models import Contact, Photo
from . forms import ContactForm, SignupForm


class HomeView(TemplateView):
    template_name = 'site_core/home.html'

class PhotoCreateView(LoginRequiredMixin, CreateView):
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    model = Photo
    fields = ['description', 'photo']
    success_url = reverse_lazy('site_core:list_photo')

class PhotoListView(LoginRequiredMixin, ListView):
    model = Photo
    context_object_name = 'photo_list'
    template_name = 'site_core/photo_list.html'

    def get_queryset(self):
        '''This method displays photos that belong to the currently logged in user.'''

        return Photo.objects.filter(owner=self.request.user)

class SignUpView(generic.CreateView):
    form_class = SignupForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'site_core/contact_form.html'
    success_url = reverse_lazy('site_core:home')

    def form_valid(self, form):
        form.send_email()
        return super(ContactView, self).form_valid(form)

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('site_core:list_photo')

def gallery(request):
    return render(request,"site_core/gallery.html")

def email_success(request):
    return render(request, "site_core/email_success.html")

def view_404(request, exception=None):
    return redirect('site_core:home')

site_core/templates/base.html
{% load static %}

<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Photo renovation website</title>
      <link rel="stylesheet" href='{% static "site_core/style.css" %}'>
  </head>
  <body>
    {% block my_header %}
      <header class='header'>
          <article>
            <h2 id = 'header_font'>Photo renovation website</h2>
          </article>
      </header>
    {% endblock %}
      <nav>
        <div class="navbar">
          <div class="container nav-container">
              <input class="checkbox" type="checkbox" name="" id="" />
              <div class="hamburger-lines">
                <span class="line line1"></span>
                <span class="line line2"></span>
                <span class="line line3"></span>
              </div>  
            <div class="logo">
              <h1>Navbar</h1>
            </div>
            <div class="menu-items">
              <li><a href="{% url 'site_core:home' %}">Home</a></li>
              <li><a href="{% url 'site_core:gallery' %}">Gallery</a></li>
              <li><a href="{% url 'site_core:create_photo' %}">Photo reconstruction</a></li>
              <li><a href="{% url 'site_core:list_photo' %}">My photos</a></li>
              <li><a href="{% url 'site_core:contact_form' %}">Contact</a></li>
              {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}?next={{request.path}}">Sign out, <strong>{{user.username}}</strong></a></li>
              {% else %}
                <li><a href="{% url 'login' %}?next={{request.path}}">Sign in</a></li>
                <li><a href="{% url 'site_core:signup' %}?next={{request.path}}">Sign up</a></li>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    {% block content %}{% endblock content %}
    <footer>
      <p>Copyright &copy; photo-renowation-website 2022</p>
    </footer>
  </body>
</html>

site_core/templates/site_core/contact_form.html
{% extends 'base.html' %}

{% block my_header %}
{% endblock %}

{% block content %}
  <section id="contact">
    <article>
      <h2>Write to us!</h2>
      <div class='form'>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <table style = 'font-family: Arial, Helvetica, sans-serif; font-size: 1.5em; color: #084012;'>
            <tr>
              <td>Subject: </td>
              <td>{{ form.subject }}</td>
            </tr>
            <tr>
              <td>Email: </td>
              <td>{{ form.email }}</td>
            </tr>
            <tr>
              <td>Message: </td>
              <td>{{ form.message }}</td>
            </tr>
          </table>
          <div class="buttonHolder">
            <input class='form_button' type="submit" value="Submit!">
          </div>
        </form>
      </div>
    </article>
  </section>
{% endblock %}

site_core/templates/site_core/email_success.html
{% extends 'base.html' %}

{% block my_header %}
{% endblock %}

{% block content %}
  <section id="contact">
    <article>
      <h2>Email has been sent!</h2>
      <div class="buttonHolder">
        <a href="{% url 'site_core:contact_form' %}"><input class='form_button' type="submit" value="I have another question."></a>
      </div>
    </article>
  </section>
{% endblock %}

site_core/templates/site_core/gallery.html
{% extends 'base.html' %}

{% block my_header %}
{% endblock %}

{% block content %}
  <section id="gallery">
      <article id="article_gallery">
        <h2 id='h2_gallery'>Gallery</h2>
        <div class="row">
          <div class="column">
            <div id='card1'></div>
            <div id='card2'></div>
          </div>
          <div class="column">
            <div id='card3'></div>
            <div id='card4'></div>
          </div>
        </div>
      </article>
    </section>     
{% endblock %}

site_core/templates/site_core/home.html
{% extends 'base.html' %}

{% block content %}
  <section id="home">
    <article>
      <h2>Photo renowation website</h2>

      <p>Do you have photos that have been damaged? Our website allows you to restore photos.</p>
      <p>Scratches, gratings are no longer a problem.  Restore your photos to their former glory.</p>
    </article>
  </section>

  <section id="gallery">
    <article id="article_gallery">
      <h2 id='h2_gallery'>Gallery</h2>
      <div class="row">
        <div class="column">
          <div id='card1'></div>
          <div id='card2'></div>
        </div>
        <div class="column">
          <div id='card3'></div>
          <div id='card4'></div>
        </div>
      </div>
    </article>
  </section>  

  <section id="contact_home">
    <article>
      <h2>Contact</h2>
      <p>Contact us using the form below. We will certainly dispel all your doubts.</p>
      <a href="{% url 'site_core:contact_form' %}"><h3 class='form_button'>Click here to contact!</h3></a>
    </article>
  </section>

{% endblock %}

site_core/templates/site_core/photo_confirm_delete.html
{% extends 'base.html' %}

{% block my_header %}
{% endblock %}

{% block content %}
  <section id="contact">
    <article>
      <h2>Are you sure you want to delete this photo?</h2>
      <div class='form'>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="buttonHolder">
              <input class='form_button' type="submit" value="Delete">
            </div>
        </form>
      </div>
    </article>
  </section>
{% endblock %}

site_core/templates/site_core/photo_form.html
{% extends 'base.html' %}

{% block my_header %}
{% endblock %}

{% block content %}
  <section id="contact">
    <article>
      <h2>Upload a photo for restoration.</h2>
      <div class='form'>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="buttonHolder">
              <input class='form_button' type="submit" value="Submit!">
            </div>
        </form>
      </div>
    </article>
  </section>
{% endblock %}

site_core/templates/site_core/photo_list.html
{% extends 'base.html' %}

{% block my_header %}
{% endblock %}

{% block content %}
  <section id="contact">
    <article>
      {% if photo_list %}
        <h2>List of sended Photos</h2>
        <hr>
          {% for photo in photo_list %}
            <div class="row">
              <div class="photo_list_col">{{photo}}</div>
              <div class="photo_list_col"><img id='list_photo' src="{{photo.photo.url}}"></div>
              <div class="photo_list_col"><a href="/photo_delete/{{photo.id}}"><input class='form_button' type="submit" value="Delete"></a></div>
            </div> 
            <hr></br>
          {% endfor %}
        <p>After completing the renovation process, photos will be sent to the email address <strong>{{user.email}}</strong></p>
      {% else %}
        <h2>You haven't uploaded any photos yet.</h2>
        <div class="buttonHolder">
          <a href="{% url 'site_core:create_photo' %}"><input class='form_button' type="submit" value="Upload a photo for restoration."></a>
        </div>
      {% endif %} 
    </article>
  </section>
{% endblock %}